spring.application.name=spotifydownloader

# Actuator (para ver logs pelo browser)
management.endpoints.web.exposure.include=logfile
management.endpoint.logfile.enabled=true

# Caminho para o Controller (e Logback)
logging.file.path=${user.home}/.spotifydownloader/logs
logging.file.name=${logging.file.path}/spotify-downloader.log
logging.level.com.hs.spotifydownloader=DEBUG